--This translation is originally a courtesy of Johann Schwarz
--https://github.com/Johann-Schwarz
UPDATE core.menu_locale SET menu_text = 'API-Richtlinien' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SAA');
UPDATE core.menu_locale SET menu_text = 'Kontoauszug' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='AS');
UPDATE core.menu_locale SET menu_text = 'Administrations Werkzeuge' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SAT');
UPDATE core.menu_locale SET menu_text = 'Alterungstafel' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='AGS');
UPDATE core.menu_locale SET menu_text = 'Prüfungsberichte' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SEAR');
UPDATE core.menu_locale SET menu_text = 'Automatische Verifizierungs  Richtlinie' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SAV');
UPDATE core.menu_locale SET menu_text = 'Back Office' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='BO');
UPDATE core.menu_locale SET menu_text = 'Datenbank sichern' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='BAK');
UPDATE core.menu_locale SET menu_text = 'Bilanz' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='BS');
UPDATE core.menu_locale SET menu_text = 'Bankkonten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='CBA');
UPDATE core.menu_locale SET menu_text = 'Bonus Tafel Zuteilung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='BSA');
UPDATE core.menu_locale SET menu_text = 'Bonus Tafel Details' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='BSD');
UPDATE core.menu_locale SET menu_text = 'Bonus Tafel für Verkäufer' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='ABS');
UPDATE core.menu_locale SET menu_text = 'Marken' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSB');
UPDATE core.menu_locale SET menu_text = 'Cashflow' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='CF');
UPDATE core.menu_locale SET menu_text = 'Cashflow Überschriften' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='CFH');
UPDATE core.menu_locale SET menu_text = 'Barwerte Depot Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SCR');
UPDATE core.menu_locale SET menu_text = 'Benutzerpasswort ändern' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PWD');
UPDATE core.menu_locale SET menu_text = 'Kontenplan' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='COA');
UPDATE core.menu_locale SET menu_text = 'Kombinierte Artikel Details' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSCD');
UPDATE core.menu_locale SET menu_text = 'Kombinierte Artikel' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSC');
UPDATE core.menu_locale SET menu_text = 'Erweiterte Masseinheiten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='CUOM');
UPDATE core.menu_locale SET menu_text = 'Kostenstellen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='CC');
UPDATE core.menu_locale SET menu_text = 'Kosten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='ICP');
UPDATE core.menu_locale SET menu_text = 'Kassen-Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SCS');
UPDATE core.menu_locale SET menu_text = 'Bezirks Umsatzsteuer' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='CTST');
UPDATE core.menu_locale SET menu_text = 'Staats-Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SCRS');
UPDATE core.menu_locale SET menu_text = 'Bezirks-Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SCTS');
UPDATE core.menu_locale SET menu_text = 'Währungsmanagement' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='CUR');
UPDATE core.menu_locale SET menu_text = 'Datenbankstatistik' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='DBSTAT');
UPDATE core.menu_locale SET menu_text = 'Abteilungs Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SDS');
UPDATE core.menu_locale SET menu_text = 'Direkt Einkauf' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='DRP');
UPDATE core.menu_locale SET menu_text = 'Direktverkauf' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='DRS');
UPDATE core.menu_locale SET menu_text = 'Tagesabschluss ' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='EOD');
UPDATE core.menu_locale SET menu_text = 'Körperschafts Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SES');
UPDATE core.menu_locale SET menu_text = 'Finanzen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='FI');
UPDATE core.menu_locale SET menu_text = 'Geschäftsjahr Informationen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SFY');
UPDATE core.menu_locale SET menu_text = 'Markierungen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='TRF');
UPDATE core.menu_locale SET menu_text = 'Perioden und Geschftsjahr Management' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SFR');
UPDATE core.menu_locale SET menu_text = 'Sachkonten Zugriffs Richtlinie' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SAP');
UPDATE core.menu_locale SET menu_text = 'Wareneingang Eintrag' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='GRN');
UPDATE core.menu_locale SET menu_text = 'Industrie-Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SIS');
UPDATE core.menu_locale SET menu_text = 'Lager Kontoauszug' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='IAS');
UPDATE core.menu_locale SET menu_text = 'Lagerbewegungen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='IIM');
UPDATE core.menu_locale SET menu_text = 'Artikelgruppen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SIG');
UPDATE core.menu_locale SET menu_text = 'Artikelpflege' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSI');
UPDATE core.menu_locale SET menu_text = 'Journal Voucher  Eintrag' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='JVN');
UPDATE core.menu_locale SET menu_text = 'Säumniszuschläge' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='LF');
UPDATE core.menu_locale SET menu_text = 'Login Form' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SEAR-LV');
UPDATE core.menu_locale SET menu_text = 'Menü-Zugriffs Richtlinien' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SMA');
UPDATE core.menu_locale SET menu_text = 'Händler Gebühren-Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='MFS');
UPDATE core.menu_locale SET menu_text = 'Verschiedene Parameter' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SMP');
UPDATE core.menu_locale SET menu_text = 'Office & Filiale einrichten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SOB');
UPDATE core.menu_locale SET menu_text = 'Office Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SOS');
UPDATE core.menu_locale SET menu_text = 'Einmalig durchführbares Setup ' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='OTS');
UPDATE core.menu_locale SET menu_text = 'Warenanfangsbestand' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='OTSI');
UPDATE core.menu_locale SET menu_text = 'Parteien-Konten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PA');
UPDATE core.menu_locale SET menu_text = 'Partei Arten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PT');
UPDATE core.menu_locale SET menu_text = 'Kreditkarten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PAC');
UPDATE core.menu_locale SET menu_text = 'Zahlungsbedingungen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PAT');
UPDATE core.menu_locale SET menu_text = 'Richtlinien Management' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SPM');
UPDATE core.menu_locale SET menu_text = 'Produkte & Angebote' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='ITM');
UPDATE core.menu_locale SET menu_text = 'Gewinn- und Verlustrechnung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PLA');
UPDATE core.menu_locale SET menu_text = 'Einkauf' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PU');
UPDATE core.menu_locale SET menu_text = 'Einkauf & eingehende Angebote' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PUQ');
UPDATE core.menu_locale SET menu_text = 'Auftragserteilung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PO');
UPDATE core.menu_locale SET menu_text = 'Waren Nachbestellung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PRO');
UPDATE core.menu_locale SET menu_text = 'Einkauf Reports' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PUR');
UPDATE core.menu_locale SET menu_text = 'Einkaufs Rücksendungen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PR');
UPDATE core.menu_locale SET menu_text = 'Empfangsbestätigung Kunde' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='RFC');
UPDATE core.menu_locale SET menu_text = 'Wiederkehrende Rechnung einrichten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='RIS');
UPDATE core.menu_locale SET menu_text = 'Wiederkehrende Rechnungen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='RI');
UPDATE core.menu_locale SET menu_text = 'Report Schreiber' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='RW');
UPDATE core.menu_locale SET menu_text = 'Reports' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='IR');
UPDATE core.menu_locale SET menu_text = 'Reports ' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='FIR');
UPDATE core.menu_locale SET menu_text = 'Rollenverwaltung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SRM');
UPDATE core.menu_locale SET menu_text = 'Vertrieb' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SA');
UPDATE core.menu_locale SET menu_text = 'Vertrieb & Voranschläge' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SAQ');
UPDATE core.menu_locale SET menu_text = 'Vertrieb Lieferung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SD');
UPDATE core.menu_locale SET menu_text = 'Eingehende Bestellungen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SO');
UPDATE core.menu_locale SET menu_text = 'Kostenvoranschläge' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SQ');
UPDATE core.menu_locale SET menu_text = 'Verkaufsberichte' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SAR');
UPDATE core.menu_locale SET menu_text = 'Rücknahmen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SR');
UPDATE core.menu_locale SET menu_text = 'Umsatzsteuer Details' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STXD');
UPDATE core.menu_locale SET menu_text = 'Umsatzsteuer Ausnahmen Details' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STXEXD');
UPDATE core.menu_locale SET menu_text = 'Umsatzsteuer Ausnahmen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STXEX');
UPDATE core.menu_locale SET menu_text = 'Umsatzsteuerarten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STXT');
UPDATE core.menu_locale SET menu_text = 'Umsatzsteuer' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STX');
UPDATE core.menu_locale SET menu_text = 'Vertriebsteams' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SST');
UPDATE core.menu_locale SET menu_text = 'Verkäufer' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSA');
UPDATE core.menu_locale SET menu_text = 'Verkaufspreise' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='ISP');
UPDATE core.menu_locale SET menu_text = 'Einrichtung und Wartung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSM');
UPDATE core.menu_locale SET menu_text = 'Einrichtung und Wartung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='ISM');
UPDATE core.menu_locale SET menu_text = 'Einrichtung und Wartung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='FSM');
UPDATE core.menu_locale SET menu_text = 'Versand Informationen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SHI');
UPDATE core.menu_locale SET menu_text = 'Lieferadressen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='PSA');
UPDATE core.menu_locale SET menu_text = 'Landes Umsatzsteuern' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STST');
UPDATE core.menu_locale SET menu_text = 'Landes Setup' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSS');
UPDATE core.menu_locale SET menu_text = 'Lager Anpassung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STA');
UPDATE core.menu_locale SET menu_text = 'Umlagerungs Journal' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STJ');
UPDATE core.menu_locale SET menu_text = 'Lager Richtlinien' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SSP');
UPDATE core.menu_locale SET menu_text = 'Geschäfts Typen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STT');
UPDATE core.menu_locale SET menu_text = 'Geschäfte' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='STO');
UPDATE core.menu_locale SET menu_text = 'Steuerbehörden' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='TXA');
UPDATE core.menu_locale SET menu_text = 'Steuerkonfiguration' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='BOTC');
UPDATE core.menu_locale SET menu_text = 'Steuer Ausnahmearten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='TXEXT');
UPDATE core.menu_locale SET menu_text = 'Steuerbasis' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='TXM');
UPDATE core.menu_locale SET menu_text = 'Meistverkaufte Artikel' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SAR-TSI');
UPDATE core.menu_locale SET menu_text = 'Transaktionen und Vorlagen' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='FTT');
UPDATE core.menu_locale SET menu_text = 'Rohbilanz' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='TB');
UPDATE core.menu_locale SET menu_text = 'Maßeinheiten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='UOM');
UPDATE core.menu_locale SET menu_text = 'Wechselkurse Updaten' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='UER');
UPDATE core.menu_locale SET menu_text = 'Benutzerverwaltung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SUM');
UPDATE core.menu_locale SET menu_text = 'Voucher Verifizierung' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='FVV');
UPDATE core.menu_locale SET menu_text = 'Voucher  Verifizierungs Richtlinie' WHERE culture = 'de' AND menu_id = (SELECT menu_id FROM core.menus WHERE menu_code='SVV');
