//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Core.Modules.Sales.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScrudResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScrudResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.Core.Modules.Sales.Resources.ScrudResource", typeof(ScrudResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id.
        /// </summary>
        internal static string account_id {
            get {
                return ResourceManager.GetString("account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master.
        /// </summary>
        internal static string account_master {
            get {
                return ResourceManager.GetString("account_master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Code.
        /// </summary>
        internal static string account_master_code {
            get {
                return ResourceManager.GetString("account_master_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Id.
        /// </summary>
        internal static string account_master_id {
            get {
                return ResourceManager.GetString("account_master_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Name.
        /// </summary>
        internal static string account_master_name {
            get {
                return ResourceManager.GetString("account_master_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string account_name {
            get {
                return ResourceManager.GetString("account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string account_number {
            get {
                return ResourceManager.GetString("account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 1.
        /// </summary>
        internal static string address_line_1 {
            get {
                return ResourceManager.GetString("address_line_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Line 2.
        /// </summary>
        internal static string address_line_2 {
            get {
                return ResourceManager.GetString("address_line_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Credit.
        /// </summary>
        internal static string allow_credit {
            get {
                return ResourceManager.GetString("allow_credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount From.
        /// </summary>
        internal static string amount_from {
            get {
                return ResourceManager.GetString("amount_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount To.
        /// </summary>
        internal static string amount_to {
            get {
                return ResourceManager.GetString("amount_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Timestamp.
        /// </summary>
        internal static string audit_ts {
            get {
                return ResourceManager.GetString("audit_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit User Id.
        /// </summary>
        internal static string audit_user_id {
            get {
                return ResourceManager.GetString("audit_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Trigger on Sales.
        /// </summary>
        internal static string auto_trigger_on_sales {
            get {
                return ResourceManager.GetString("auto_trigger_on_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Rate.
        /// </summary>
        internal static string bonus_rate {
            get {
                return ResourceManager.GetString("bonus_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Code.
        /// </summary>
        internal static string bonus_slab_code {
            get {
                return ResourceManager.GetString("bonus_slab_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Detail Id.
        /// </summary>
        internal static string bonus_slab_detail_id {
            get {
                return ResourceManager.GetString("bonus_slab_detail_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;AmountTo&quot; must be greater than &quot;AmountFrom&quot;..
        /// </summary>
        internal static string bonus_slab_details_amounts_chk {
            get {
                return ResourceManager.GetString("bonus_slab_details_amounts_chk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Id.
        /// </summary>
        internal static string bonus_slab_id {
            get {
                return ResourceManager.GetString("bonus_slab_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Name.
        /// </summary>
        internal static string bonus_slab_name {
            get {
                return ResourceManager.GetString("bonus_slab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string brand {
            get {
                return ResourceManager.GetString("brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        internal static string cell {
            get {
                return ResourceManager.GetString("cell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Frequency.
        /// </summary>
        internal static string checking_frequency {
            get {
                return ResourceManager.GetString("checking_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Frequency Id.
        /// </summary>
        internal static string checking_frequency_id {
            get {
                return ResourceManager.GetString("checking_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string city {
            get {
                return ResourceManager.GetString("city", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Rate.
        /// </summary>
        internal static string commision_rate {
            get {
                return ResourceManager.GetString("commision_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Rate.
        /// </summary>
        internal static string commission_rate {
            get {
                return ResourceManager.GetString("commission_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Item.
        /// </summary>
        internal static string compound_item {
            get {
                return ResourceManager.GetString("compound_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Item Id.
        /// </summary>
        internal static string compound_item_id {
            get {
                return ResourceManager.GetString("compound_item_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confidential.
        /// </summary>
        internal static string confidential {
            get {
                return ResourceManager.GetString("confidential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string contact_number {
            get {
                return ResourceManager.GetString("contact_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price.
        /// </summary>
        internal static string cost_price {
            get {
                return ResourceManager.GetString("cost_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Price Includes Tax.
        /// </summary>
        internal static string cost_price_includes_tax {
            get {
                return ResourceManager.GetString("cost_price_includes_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string country {
            get {
                return ResourceManager.GetString("country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CST Number.
        /// </summary>
        internal static string cst_number {
            get {
                return ResourceManager.GetString("cst_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string currency {
            get {
                return ResourceManager.GetString("currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Days.
        /// </summary>
        internal static string due_days {
            get {
                return ResourceManager.GetString("due_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Frequency.
        /// </summary>
        internal static string due_frequency {
            get {
                return ResourceManager.GetString("due_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Frequency Id.
        /// </summary>
        internal static string due_frequency_id {
            get {
                return ResourceManager.GetString("due_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due on Date.
        /// </summary>
        internal static string due_on_date {
            get {
                return ResourceManager.GetString("due_on_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From.
        /// </summary>
        internal static string effective_from {
            get {
                return ResourceManager.GetString("effective_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends On.
        /// </summary>
        internal static string ends_on {
            get {
                return ResourceManager.GetString("ends_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Code.
        /// </summary>
        internal static string external_code {
            get {
                return ResourceManager.GetString("external_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string fax {
            get {
                return ResourceManager.GetString("fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string first_name {
            get {
                return ResourceManager.GetString("first_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Code.
        /// </summary>
        internal static string frequency_code {
            get {
                return ResourceManager.GetString("frequency_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Id.
        /// </summary>
        internal static string frequency_id {
            get {
                return ResourceManager.GetString("frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Name.
        /// </summary>
        internal static string frequency_name {
            get {
                return ResourceManager.GetString("frequency_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Head.
        /// </summary>
        internal static string gl_head {
            get {
                return ResourceManager.GetString("gl_head", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Period.
        /// </summary>
        internal static string grace_period {
            get {
                return ResourceManager.GetString("grace_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Child.
        /// </summary>
        internal static string has_child {
            get {
                return ResourceManager.GetString("has_child", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hight In Centimeters.
        /// </summary>
        internal static string height_in_centimeters {
            get {
                return ResourceManager.GetString("height_in_centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hot Item.
        /// </summary>
        internal static string hot_item {
            get {
                return ResourceManager.GetString("hot_item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        internal static string is_active {
            get {
                return ResourceManager.GetString("is_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Flat Amount.
        /// </summary>
        internal static string is_flat_amount {
            get {
                return ResourceManager.GetString("is_flat_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Supplier.
        /// </summary>
        internal static string is_supplier {
            get {
                return ResourceManager.GetString("is_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Transaction Node.
        /// </summary>
        internal static string is_transaction_node {
            get {
                return ResourceManager.GetString("is_transaction_node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string item {
            get {
                return ResourceManager.GetString("item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string item_code {
            get {
                return ResourceManager.GetString("item_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Group.
        /// </summary>
        internal static string item_group {
            get {
                return ResourceManager.GetString("item_group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        internal static string item_id {
            get {
                return ResourceManager.GetString("item_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string item_name {
            get {
                return ResourceManager.GetString("item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string last_name {
            get {
                return ResourceManager.GetString("last_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee.
        /// </summary>
        internal static string late_fee {
            get {
                return ResourceManager.GetString("late_fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Code.
        /// </summary>
        internal static string late_fee_code {
            get {
                return ResourceManager.GetString("late_fee_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Id.
        /// </summary>
        internal static string late_fee_id {
            get {
                return ResourceManager.GetString("late_fee_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Name.
        /// </summary>
        internal static string late_fee_name {
            get {
                return ResourceManager.GetString("late_fee_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Posting Frequency.
        /// </summary>
        internal static string late_fee_posting_frequency {
            get {
                return ResourceManager.GetString("late_fee_posting_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Posting Frequency Id.
        /// </summary>
        internal static string late_fee_posting_frequency_id {
            get {
                return ResourceManager.GetString("late_fee_posting_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Time In Days.
        /// </summary>
        internal static string lead_time_in_days {
            get {
                return ResourceManager.GetString("lead_time_in_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length In Centimeters.
        /// </summary>
        internal static string length_in_centimeters {
            get {
                return ResourceManager.GetString("length_in_centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machinable.
        /// </summary>
        internal static string machinable {
            get {
                return ResourceManager.GetString("machinable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Stok.
        /// </summary>
        internal static string maintain_stock {
            get {
                return ResourceManager.GetString("maintain_stock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Credit Amount.
        /// </summary>
        internal static string maximum_credit_amount {
            get {
                return ResourceManager.GetString("maximum_credit_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Credit Period.
        /// </summary>
        internal static string maximum_credit_period {
            get {
                return ResourceManager.GetString("maximum_credit_period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        internal static string middle_name {
            get {
                return ResourceManager.GetString("middle_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pan Number.
        /// </summary>
        internal static string pan_number {
            get {
                return ResourceManager.GetString("pan_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent.
        /// </summary>
        internal static string parent {
            get {
                return ResourceManager.GetString("parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Id.
        /// </summary>
        internal static string parent_account_id {
            get {
                return ResourceManager.GetString("parent_account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Name.
        /// </summary>
        internal static string parent_account_name {
            get {
                return ResourceManager.GetString("parent_account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Number.
        /// </summary>
        internal static string parent_account_number {
            get {
                return ResourceManager.GetString("parent_account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party.
        /// </summary>
        internal static string party {
            get {
                return ResourceManager.GetString("party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Code.
        /// </summary>
        internal static string party_code {
            get {
                return ResourceManager.GetString("party_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Id.
        /// </summary>
        internal static string party_id {
            get {
                return ResourceManager.GetString("party_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Name.
        /// </summary>
        internal static string party_name {
            get {
                return ResourceManager.GetString("party_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type.
        /// </summary>
        internal static string party_type {
            get {
                return ResourceManager.GetString("party_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Type Id.
        /// </summary>
        internal static string party_type_id {
            get {
                return ResourceManager.GetString("party_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term.
        /// </summary>
        internal static string payment_term {
            get {
                return ResourceManager.GetString("payment_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term Code.
        /// </summary>
        internal static string payment_term_code {
            get {
                return ResourceManager.GetString("payment_term_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term Id.
        /// </summary>
        internal static string payment_term_id {
            get {
                return ResourceManager.GetString("payment_term_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term Name.
        /// </summary>
        internal static string payment_term_name {
            get {
                return ResourceManager.GetString("payment_term_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Shipping Mail Type.
        /// </summary>
        internal static string preferred_shipping_mail_type {
            get {
                return ResourceManager.GetString("preferred_shipping_mail_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Shipping Package Shape.
        /// </summary>
        internal static string preferred_shipping_package_shape {
            get {
                return ResourceManager.GetString("preferred_shipping_package_shape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferred Supplier.
        /// </summary>
        internal static string preferred_supplier {
            get {
                return ResourceManager.GetString("preferred_supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurrence Type Id.
        /// </summary>
        internal static string recurrence_type_id {
            get {
                return ResourceManager.GetString("recurrence_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Amount.
        /// </summary>
        internal static string recurring_amount {
            get {
                return ResourceManager.GetString("recurring_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Duration.
        /// </summary>
        internal static string recurring_duration {
            get {
                return ResourceManager.GetString("recurring_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Frequency.
        /// </summary>
        internal static string recurring_frequency {
            get {
                return ResourceManager.GetString("recurring_frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Frequency Id.
        /// </summary>
        internal static string recurring_frequency_id {
            get {
                return ResourceManager.GetString("recurring_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice.
        /// </summary>
        internal static string recurring_invoice {
            get {
                return ResourceManager.GetString("recurring_invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Code.
        /// </summary>
        internal static string recurring_invoice_code {
            get {
                return ResourceManager.GetString("recurring_invoice_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Id.
        /// </summary>
        internal static string recurring_invoice_id {
            get {
                return ResourceManager.GetString("recurring_invoice_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Name.
        /// </summary>
        internal static string recurring_invoice_name {
            get {
                return ResourceManager.GetString("recurring_invoice_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Setup Id.
        /// </summary>
        internal static string recurring_invoice_setup_id {
            get {
                return ResourceManager.GetString("recurring_invoice_setup_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have more than one auto trigger on sales for this item..
        /// </summary>
        internal static string recurring_invoices_item_id_auto_trigger_on_sales_uix {
            get {
                return ResourceManager.GetString("recurring_invoices_item_id_auto_trigger_on_sales_uix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurs on Same Calendar Date.
        /// </summary>
        internal static string recurs_on_same_calendar_date {
            get {
                return ResourceManager.GetString("recurs_on_same_calendar_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        internal static string reorder_level {
            get {
                return ResourceManager.GetString("reorder_level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Quantity.
        /// </summary>
        internal static string reorder_quantity {
            get {
                return ResourceManager.GetString("reorder_quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Unit.
        /// </summary>
        internal static string reorder_unit {
            get {
                return ResourceManager.GetString("reorder_unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax.
        /// </summary>
        internal static string sales_tax {
            get {
                return ResourceManager.GetString("sales_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team Code.
        /// </summary>
        internal static string sales_team_code {
            get {
                return ResourceManager.GetString("sales_team_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team Id.
        /// </summary>
        internal static string sales_team_id {
            get {
                return ResourceManager.GetString("sales_team_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team Name.
        /// </summary>
        internal static string sales_team_name {
            get {
                return ResourceManager.GetString("sales_team_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Bonus Setup Id.
        /// </summary>
        internal static string salesperson_bonus_setup_id {
            get {
                return ResourceManager.GetString("salesperson_bonus_setup_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Code.
        /// </summary>
        internal static string salesperson_code {
            get {
                return ResourceManager.GetString("salesperson_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Id.
        /// </summary>
        internal static string salesperson_id {
            get {
                return ResourceManager.GetString("salesperson_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Name.
        /// </summary>
        internal static string salesperson_name {
            get {
                return ResourceManager.GetString("salesperson_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price.
        /// </summary>
        internal static string selling_price {
            get {
                return ResourceManager.GetString("selling_price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selling Price Includes Tax.
        /// </summary>
        internal static string selling_price_includes_tax {
            get {
                return ResourceManager.GetString("selling_price_includes_tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab Name.
        /// </summary>
        internal static string slab_name {
            get {
                return ResourceManager.GetString("slab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SST Number.
        /// </summary>
        internal static string sst_number {
            get {
                return ResourceManager.GetString("sst_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts From.
        /// </summary>
        internal static string starts_from {
            get {
                return ResourceManager.GetString("starts_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        internal static string state {
            get {
                return ResourceManager.GetString("state", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Reference.
        /// </summary>
        internal static string statement_reference {
            get {
                return ResourceManager.GetString("statement_reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string street {
            get {
                return ResourceManager.GetString("street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string sub_total {
            get {
                return ResourceManager.GetString("sub_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys Type.
        /// </summary>
        internal static string sys_type {
            get {
                return ResourceManager.GetString("sys_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duration.
        /// </summary>
        internal static string total_duration {
            get {
                return ResourceManager.GetString("total_duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        internal static string total_sales {
            get {
                return ResourceManager.GetString("total_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string unit {
            get {
                return ResourceManager.GetString("unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string unit_name {
            get {
                return ResourceManager.GetString("unit_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        internal static string url {
            get {
                return ResourceManager.GetString("url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight In Grams.
        /// </summary>
        internal static string weight_in_grams {
            get {
                return ResourceManager.GetString("weight_in_grams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width In Centimeters.
        /// </summary>
        internal static string width_in_centimeters {
            get {
                return ResourceManager.GetString("width_in_centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Code.
        /// </summary>
        internal static string zip_code {
            get {
                return ResourceManager.GetString("zip_code", resourceCulture);
            }
        }
    }
}
