//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Core.Modules.Sales.Widgets {
    
    
    public partial class TopSellingProductOfAllTimeCurrentWidget {
        
        /// <summary>
        /// TopSellingProductsLiteral control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal TopSellingProductsLiteral;
        
        /// <summary>
        /// TopSellingProductsOfAllTimeGridView control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView TopSellingProductsOfAllTimeGridView;
    }
}
