//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.DbFactory.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DbErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DbErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.DbFactory.Resources.DbErrors", typeof(DbErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot calculate interest. The number of days in a year was not provided..
        /// </summary>
        internal static string P1301 {
            get {
                return ResourceManager.GetString("P1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid data..
        /// </summary>
        internal static string P3000 {
            get {
                return ResourceManager.GetString("P3000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid user name..
        /// </summary>
        internal static string P3001 {
            get {
                return ResourceManager.GetString("P3001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        internal static string P3005 {
            get {
                return ResourceManager.GetString("P3005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please provide a new password..
        /// </summary>
        internal static string P3006 {
            get {
                return ResourceManager.GetString("P3006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value date..
        /// </summary>
        internal static string P3007 {
            get {
                return ResourceManager.GetString("P3007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date..
        /// </summary>
        internal static string P3008 {
            get {
                return ResourceManager.GetString("P3008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid period specified..
        /// </summary>
        internal static string P3009 {
            get {
                return ResourceManager.GetString("P3009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid office id..
        /// </summary>
        internal static string P3010 {
            get {
                return ResourceManager.GetString("P3010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid office..
        /// </summary>
        internal static string P3011 {
            get {
                return ResourceManager.GetString("P3011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid store..
        /// </summary>
        internal static string P3012 {
            get {
                return ResourceManager.GetString("P3012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid cash repository..
        /// </summary>
        internal static string P3013 {
            get {
                return ResourceManager.GetString("P3013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid party..
        /// </summary>
        internal static string P3050 {
            get {
                return ResourceManager.GetString("P3050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid item..
        /// </summary>
        internal static string P3051 {
            get {
                return ResourceManager.GetString("P3051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid unit..
        /// </summary>
        internal static string P3052 {
            get {
                return ResourceManager.GetString("P3052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or incompatible unit..
        /// </summary>
        internal static string P3053 {
            get {
                return ResourceManager.GetString("P3053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The reorder unit is incompatible with the base unit..
        /// </summary>
        internal static string P3054 {
            get {
                return ResourceManager.GetString("P3054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid exchange rate..
        /// </summary>
        internal static string P3055 {
            get {
                return ResourceManager.GetString("P3055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid LoginId..
        /// </summary>
        internal static string P3101 {
            get {
                return ResourceManager.GetString("P3101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current password is incorrect..
        /// </summary>
        internal static string P3105 {
            get {
                return ResourceManager.GetString("P3105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item/unit mismatch..
        /// </summary>
        internal static string P3201 {
            get {
                return ResourceManager.GetString("P3201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax form mismatch..
        /// </summary>
        internal static string P3202 {
            get {
                return ResourceManager.GetString("P3202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid quantity..
        /// </summary>
        internal static string P3301 {
            get {
                return ResourceManager.GetString("P3301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid transaction id..
        /// </summary>
        internal static string P3302 {
            get {
                return ResourceManager.GetString("P3302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The column account_id cannot be null..
        /// </summary>
        internal static string P3501 {
            get {
                return ResourceManager.GetString("P3501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange rate between the currencies was not found..
        /// </summary>
        internal static string P4010 {
            get {
                return ResourceManager.GetString("P4010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This item is not associated with this transaction..
        /// </summary>
        internal static string P4020 {
            get {
                return ResourceManager.GetString("P4020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No verification policy found for this user..
        /// </summary>
        internal static string P4030 {
            get {
                return ResourceManager.GetString("P4030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ask someone else to verify your transaction..
        /// </summary>
        internal static string P4031 {
            get {
                return ResourceManager.GetString("P4031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referencing sides are not equal..
        /// </summary>
        internal static string P5000 {
            get {
                return ResourceManager.GetString("P5000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Negative stock is not allowed..
        /// </summary>
        internal static string P5001 {
            get {
                return ResourceManager.GetString("P5001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posting this transaction would produce a negative cash balance..
        /// </summary>
        internal static string P5002 {
            get {
                return ResourceManager.GetString("P5002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Past dated transactions are not allowed..
        /// </summary>
        internal static string P5010 {
            get {
                return ResourceManager.GetString("P5010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This establishment does not allow transaction posting..
        /// </summary>
        internal static string P5100 {
            get {
                return ResourceManager.GetString("P5100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot post transaction during restricted transaction mode..
        /// </summary>
        internal static string P5101 {
            get {
                return ResourceManager.GetString("P5101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot provide sales tax information for non taxable sales..
        /// </summary>
        internal static string P5110 {
            get {
                return ResourceManager.GetString("P5110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid bank transaction information provided..
        /// </summary>
        internal static string P5111 {
            get {
                return ResourceManager.GetString("P5111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A stock adjustment entry can not contain debit item(s)..
        /// </summary>
        internal static string P5201 {
            get {
                return ResourceManager.GetString("P5201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An item can appear only once in a store..
        /// </summary>
        internal static string P5202 {
            get {
                return ResourceManager.GetString("P5202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned quantity cannot be greater than actual quantity..
        /// </summary>
        internal static string P5203 {
            get {
                return ResourceManager.GetString("P5203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The returned amount cannot be greater than actual amount..
        /// </summary>
        internal static string P5204 {
            get {
                return ResourceManager.GetString("P5204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid or rejected transaction..
        /// </summary>
        internal static string P5301 {
            get {
                return ResourceManager.GetString("P5301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient item quantity..
        /// </summary>
        internal static string P5500 {
            get {
                return ResourceManager.GetString("P5500", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a transaction is not allowed. Mark the transaction as rejected instead..
        /// </summary>
        internal static string P5800 {
            get {
                return ResourceManager.GetString("P5800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please ask someone else to verify the transaction you posted..
        /// </summary>
        internal static string P5901 {
            get {
                return ResourceManager.GetString("P5901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self verification limit exceeded. The transaction was not verified..
        /// </summary>
        internal static string P5910 {
            get {
                return ResourceManager.GetString("P5910", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales verification limit exceeded. The transaction was not verified..
        /// </summary>
        internal static string P5911 {
            get {
                return ResourceManager.GetString("P5911", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase verification limit exceeded. The transaction was not verified..
        /// </summary>
        internal static string P5912 {
            get {
                return ResourceManager.GetString("P5912", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL verification limit exceeded. The transaction was not verified..
        /// </summary>
        internal static string P5913 {
            get {
                return ResourceManager.GetString("P5913", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid configuration: COGS method..
        /// </summary>
        internal static string P6010 {
            get {
                return ResourceManager.GetString("P6010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot produce P/L statement of office(s) having different base currencies..
        /// </summary>
        internal static string P8001 {
            get {
                return ResourceManager.GetString("P8001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot produce trial balance of office(s) having different base currencies..
        /// </summary>
        internal static string P8002 {
            get {
                return ResourceManager.GetString("P8002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have a different currency on the mapped GL account..
        /// </summary>
        internal static string P8003 {
            get {
                return ResourceManager.GetString("P8003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EOD operation was already initialized..
        /// </summary>
        internal static string P8101 {
            get {
                return ResourceManager.GetString("P8101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only one column is required..
        /// </summary>
        internal static string P8501 {
            get {
                return ResourceManager.GetString("P8501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot update column..
        /// </summary>
        internal static string P8502 {
            get {
                return ResourceManager.GetString("P8502", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to change system accounts..
        /// </summary>
        internal static string P8990 {
            get {
                return ResourceManager.GetString("P8990", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to add system accounts..
        /// </summary>
        internal static string P8991 {
            get {
                return ResourceManager.GetString("P8991", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A sys user cannot have a password..
        /// </summary>
        internal static string P8992 {
            get {
                return ResourceManager.GetString("P8992", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied..
        /// </summary>
        internal static string P9001 {
            get {
                return ResourceManager.GetString("P9001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. You are not authorized to post this transaction..
        /// </summary>
        internal static string P9010 {
            get {
                return ResourceManager.GetString("P9010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. Invalid values supplied..
        /// </summary>
        internal static string P9011 {
            get {
                return ResourceManager.GetString("P9011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied! A stock adjustment transaction cannot references multiple branches..
        /// </summary>
        internal static string P9012 {
            get {
                return ResourceManager.GetString("P9012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied! A stock journal transaction cannot references multiple branches..
        /// </summary>
        internal static string P9013 {
            get {
                return ResourceManager.GetString("P9013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. You cannot verify a transaction of another office..
        /// </summary>
        internal static string P9014 {
            get {
                return ResourceManager.GetString("P9014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. You cannot verify past or futuer dated transaction..
        /// </summary>
        internal static string P9015 {
            get {
                return ResourceManager.GetString("P9015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. You don&apos;&apos;t have the right to verify the transaction..
        /// </summary>
        internal static string P9016 {
            get {
                return ResourceManager.GetString("P9016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. You don&apos;&apos;t have the right to withdraw the transaction..
        /// </summary>
        internal static string P9017 {
            get {
                return ResourceManager.GetString("P9017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acess is denied. You cannot update the &quot;transaction_details&quot; table..
        /// </summary>
        internal static string P9201 {
            get {
                return ResourceManager.GetString("P9201", resourceCulture);
            }
        }
    }
}
