//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Core.Modules.Finance.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.Core.Modules.Finance.Resources.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Code.
        /// </summary>
        internal static string AccountCode {
            get {
                return ResourceManager.GetString("AccountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ageing Slabs.
        /// </summary>
        internal static string AgeingSlabs {
            get {
                return ResourceManager.GetString("AgeingSlabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments (+).
        /// </summary>
        internal static string AttachmentsPlus {
            get {
                return ResourceManager.GetString("AttachmentsPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank Accounts.
        /// </summary>
        internal static string BankAccounts {
            get {
                return ResourceManager.GetString("BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repository.
        /// </summary>
        internal static string CashRepository {
            get {
                return ResourceManager.GetString("CashRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chart of Accounts.
        /// </summary>
        internal static string ChartOfAccounts {
            get {
                return ResourceManager.GetString("ChartOfAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Center.
        /// </summary>
        internal static string CostCenter {
            get {
                return ResourceManager.GetString("CostCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost Centers.
        /// </summary>
        internal static string CostCenters {
            get {
                return ResourceManager.GetString("CostCenters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string Credit {
            get {
                return ResourceManager.GetString("Credit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Total.
        /// </summary>
        internal static string CreditTotal {
            get {
                return ResourceManager.GetString("CreditTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + A.
        /// </summary>
        internal static string CtrlAltA {
            get {
                return ResourceManager.GetString("CtrlAltA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + C.
        /// </summary>
        internal static string CtrlAltC {
            get {
                return ResourceManager.GetString("CtrlAltC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + C.
        /// </summary>
        internal static string CtrlAltC1 {
            get {
                return ResourceManager.GetString("CtrlAltC1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + D.
        /// </summary>
        internal static string CtrlAltD {
            get {
                return ResourceManager.GetString("CtrlAltD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + D.
        /// </summary>
        internal static string CtrlAltD1 {
            get {
                return ResourceManager.GetString("CtrlAltD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + S.
        /// </summary>
        internal static string CtrlAltS {
            get {
                return ResourceManager.GetString("CtrlAltS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Alt + T.
        /// </summary>
        internal static string CtrlAltT {
            get {
                return ResourceManager.GetString("CtrlAltT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ctrl + Return.
        /// </summary>
        internal static string CtrlReturn {
            get {
                return ResourceManager.GetString("CtrlReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string Currencies {
            get {
                return ResourceManager.GetString("Currencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string Debit {
            get {
                return ResourceManager.GetString("Debit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Total.
        /// </summary>
        internal static string DebitTotal {
            get {
                return ResourceManager.GetString("DebitTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ER.
        /// </summary>
        internal static string ER {
            get {
                return ResourceManager.GetString("ER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Voucher Entry.
        /// </summary>
        internal static string JournalVoucherEntry {
            get {
                return ResourceManager.GetString("JournalVoucherEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC Credit.
        /// </summary>
        internal static string LCCredit {
            get {
                return ResourceManager.GetString("LCCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC Debit.
        /// </summary>
        internal static string LCDebit {
            get {
                return ResourceManager.GetString("LCDebit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Transaction.
        /// </summary>
        internal static string PostTransaction {
            get {
                return ResourceManager.GetString("PostTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference Number.
        /// </summary>
        internal static string ReferenceNumber {
            get {
                return ResourceManager.GetString("ReferenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Total.
        /// </summary>
        internal static string RunningTotal {
            get {
                return ResourceManager.GetString("RunningTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statement Reference.
        /// </summary>
        internal static string StatementReference {
            get {
                return ResourceManager.GetString("StatementReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Setup.
        /// </summary>
        internal static string TaxSetup {
            get {
                return ResourceManager.GetString("TaxSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Types.
        /// </summary>
        internal static string TaxTypes {
            get {
                return ResourceManager.GetString("TaxTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value Date.
        /// </summary>
        internal static string ValueDate {
            get {
                return ResourceManager.GetString("ValueDate", resourceCulture);
            }
        }
    }
}
