//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Core.Modules.POS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScrudResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScrudResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.Core.Modules.POS.Resources.ScrudResource", typeof(ScrudResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Sales.
        /// </summary>
        internal static string allow_sales {
            get {
                return ResourceManager.GetString("allow_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Timestamp.
        /// </summary>
        internal static string audit_ts {
            get {
                return ResourceManager.GetString("audit_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit User Id.
        /// </summary>
        internal static string audit_user_id {
            get {
                return ResourceManager.GetString("audit_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repository Id.
        /// </summary>
        internal static string cash_repository_id {
            get {
                return ResourceManager.GetString("cash_repository_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Code.
        /// </summary>
        internal static string counter_code {
            get {
                return ResourceManager.GetString("counter_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Id.
        /// </summary>
        internal static string counter_id {
            get {
                return ResourceManager.GetString("counter_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counter Name.
        /// </summary>
        internal static string counter_name {
            get {
                return ResourceManager.GetString("counter_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Exemption.
        /// </summary>
        internal static string is_exemption {
            get {
                return ResourceManager.GetString("is_exemption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Id.
        /// </summary>
        internal static string office_id {
            get {
                return ResourceManager.GetString("office_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax Code.
        /// </summary>
        internal static string sales_tax_code {
            get {
                return ResourceManager.GetString("sales_tax_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax Id.
        /// </summary>
        internal static string sales_tax_id {
            get {
                return ResourceManager.GetString("sales_tax_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax Name.
        /// </summary>
        internal static string sales_tax_name {
            get {
                return ResourceManager.GetString("sales_tax_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Code.
        /// </summary>
        internal static string store_code {
            get {
                return ResourceManager.GetString("store_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Id.
        /// </summary>
        internal static string store_id {
            get {
                return ResourceManager.GetString("store_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Name.
        /// </summary>
        internal static string store_name {
            get {
                return ResourceManager.GetString("store_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type Code.
        /// </summary>
        internal static string store_type_code {
            get {
                return ResourceManager.GetString("store_type_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type Id.
        /// </summary>
        internal static string store_type_id {
            get {
                return ResourceManager.GetString("store_type_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Store Type Name.
        /// </summary>
        internal static string store_type_name {
            get {
                return ResourceManager.GetString("store_type_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chosen SalesTaxId is invalid for this office..
        /// </summary>
        internal static string stores_sales_tax_id_chk {
            get {
                return ResourceManager.GetString("stores_sales_tax_id_chk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Master Id.
        /// </summary>
        internal static string tax_master_id {
            get {
                return ResourceManager.GetString("tax_master_id", resourceCulture);
            }
        }
    }
}
