//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Core.Modules.BackOffice.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Titles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Titles() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.Core.Modules.BackOffice.Resources.Titles", typeof(Titles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyze Databse.
        /// </summary>
        internal static string AnalyzeDatabse {
            get {
                return ResourceManager.GetString("AnalyzeDatabse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoverification Policy.
        /// </summary>
        internal static string AutoVerificationPolicy {
            get {
                return ResourceManager.GetString("AutoVerificationPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Console.
        /// </summary>
        internal static string BackupConsole {
            get {
                return ResourceManager.GetString("BackupConsole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Database.
        /// </summary>
        internal static string BackupDatabase {
            get {
                return ResourceManager.GetString("BackupDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup Now.
        /// </summary>
        internal static string BackupNow {
            get {
                return ResourceManager.GetString("BackupNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cash Repositories.
        /// </summary>
        internal static string CashRepositories {
            get {
                return ResourceManager.GetString("CashRepositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counters.
        /// </summary>
        internal static string Counters {
            get {
                return ResourceManager.GetString("Counters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counties.
        /// </summary>
        internal static string Counties {
            get {
                return ResourceManager.GetString("Counties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Countries.
        /// </summary>
        internal static string Countries {
            get {
                return ResourceManager.GetString("Countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County Sales Taxes.
        /// </summary>
        internal static string CountySalesTaxes {
            get {
                return ResourceManager.GetString("CountySalesTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Backups.
        /// </summary>
        internal static string DatabaseBackups {
            get {
                return ResourceManager.GetString("DatabaseBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database Statistics.
        /// </summary>
        internal static string DatabaseStatistics {
            get {
                return ResourceManager.GetString("DatabaseStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departments.
        /// </summary>
        internal static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Backup Name.
        /// </summary>
        internal static string EnterBackupName {
            get {
                return ResourceManager.GetString("EnterBackupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a New Password.
        /// </summary>
        internal static string EnterNewPassword {
            get {
                return ResourceManager.GetString("EnterNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entities.
        /// </summary>
        internal static string Entities {
            get {
                return ResourceManager.GetString("Entities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute.
        /// </summary>
        internal static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Year.
        /// </summary>
        internal static string FiscalYear {
            get {
                return ResourceManager.GetString("FiscalYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags.
        /// </summary>
        internal static string Flags {
            get {
                return ResourceManager.GetString("Flags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequencies.
        /// </summary>
        internal static string Frequencies {
            get {
                return ResourceManager.GetString("Frequencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoToTop.
        /// </summary>
        internal static string GoToTop {
            get {
                return ResourceManager.GetString("GoToTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Industries.
        /// </summary>
        internal static string Industries {
            get {
                return ResourceManager.GetString("Industries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Setup.
        /// </summary>
        internal static string OfficeSetup {
            get {
                return ResourceManager.GetString("OfficeSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password was updated..
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prepared On.
        /// </summary>
        internal static string PreparedOn {
            get {
                return ResourceManager.GetString("PreparedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax Details.
        /// </summary>
        internal static string SalesTaxDetails {
            get {
                return ResourceManager.GetString("SalesTaxDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Taxes.
        /// </summary>
        internal static string SalesTaxes {
            get {
                return ResourceManager.GetString("SalesTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax Exempt Details.
        /// </summary>
        internal static string SalesTaxExemptDetails {
            get {
                return ResourceManager.GetString("SalesTaxExemptDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax Exempts.
        /// </summary>
        internal static string SalesTaxExempts {
            get {
                return ResourceManager.GetString("SalesTaxExempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Tax Types.
        /// </summary>
        internal static string SalesTaxTypes {
            get {
                return ResourceManager.GetString("SalesTaxTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select User.
        /// </summary>
        internal static string SelectUser {
            get {
                return ResourceManager.GetString("SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to States.
        /// </summary>
        internal static string States {
            get {
                return ResourceManager.GetString("States", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State Sales Taxes.
        /// </summary>
        internal static string StateSalesTaxes {
            get {
                return ResourceManager.GetString("StateSalesTaxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Authorities.
        /// </summary>
        internal static string TaxAuthorities {
            get {
                return ResourceManager.GetString("TaxAuthorities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Exempt Types.
        /// </summary>
        internal static string TaxExemptTypes {
            get {
                return ResourceManager.GetString("TaxExemptTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Master.
        /// </summary>
        internal static string TaxMaster {
            get {
                return ResourceManager.GetString("TaxMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tel.
        /// </summary>
        internal static string Tel {
            get {
                return ResourceManager.GetString("Tel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum Database.
        /// </summary>
        internal static string VacuumDatabase {
            get {
                return ResourceManager.GetString("VacuumDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vacuum Database (Full).
        /// </summary>
        internal static string VacuumFullDatabase {
            get {
                return ResourceManager.GetString("VacuumFullDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Backups.
        /// </summary>
        internal static string ViewBackups {
            get {
                return ResourceManager.GetString("ViewBackups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher Verification Policy.
        /// </summary>
        internal static string VoucherVerificationPolicy {
            get {
                return ResourceManager.GetString("VoucherVerificationPolicy", resourceCulture);
            }
        }
    }
}
