//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.WebControls.TransactionChecklist.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.WebControls.TransactionChecklist.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot withdraw transaction. This is a not a valid GL transaction..
        /// </summary>
        internal static string CannotWithdrawNotValidGLTransaction {
            get {
                return ResourceManager.GetString("CannotWithdrawNotValidGLTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot withdraw transaction..
        /// </summary>
        internal static string CannotWithdrawTransaction {
            get {
                return ResourceManager.GetString("CannotWithdrawTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h2&gt;Hi,&lt;/h2&gt;&lt;p&gt;Please find the attached document.&lt;/p&gt;&lt;p&gt;Thank you.&lt;br /&gt;MixERP&lt;/p&gt;.
        /// </summary>
        internal static string EmailBody {
            get {
                return ResourceManager.GetString("EmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An email was sent to {0}..
        /// </summary>
        internal static string EmailSentConfirmation {
            get {
                return ResourceManager.GetString("EmailSentConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        internal static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction was approved by {0} on {1}..
        /// </summary>
        internal static string TransactionApprovedDetails {
            get {
                return ResourceManager.GetString("TransactionApprovedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction was automatically approved by {0} on {1}..
        /// </summary>
        internal static string TransactionAutoApprovedDetails {
            get {
                return ResourceManager.GetString("TransactionAutoApprovedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction is awaiting verification from an administrator..
        /// </summary>
        internal static string TransactionAwaitingVerification {
            get {
                return ResourceManager.GetString("TransactionAwaitingVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction was closed by {0} on {1}. Reason: &quot;{2}&quot;..
        /// </summary>
        internal static string TransactionClosedDetails {
            get {
                return ResourceManager.GetString("TransactionClosedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction was posted successfully..
        /// </summary>
        internal static string TransactionPostedSuccessfully {
            get {
                return ResourceManager.GetString("TransactionPostedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction was rejected by {0} on {1}. Reason: &quot;{2}&quot;..
        /// </summary>
        internal static string TransactionRejectedDetails {
            get {
                return ResourceManager.GetString("TransactionRejectedDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you withdraw a transaction, it won&apos;t be forwarded to the workflow module. This means that your withdrawn transactions are rejected and require no further verification. However, you won&apos;t be able to unwithdraw this transaction later..
        /// </summary>
        internal static string TransactionWithdrawalInformation {
            get {
                return ResourceManager.GetString("TransactionWithdrawalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This transaction was withdrawn by {0} on {1}. Reason: &quot;{2}&quot;..
        /// </summary>
        internal static string TransactionWithdrawnDetails {
            get {
                return ResourceManager.GetString("TransactionWithdrawnDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The transaction was withdrawn successfully. Moreover, this action will affect the all the reports produced on and after &quot;{0}&quot;..
        /// </summary>
        internal static string TransactionWithdrawnMessage {
            get {
                return ResourceManager.GetString("TransactionWithdrawnMessage", resourceCulture);
            }
        }
    }
}
