//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Core.Modules.CRM.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScrudResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScrudResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.Core.Modules.CRM.Resources.ScrudResource", typeof(ScrudResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Timestamp.
        /// </summary>
        internal static string audit_ts {
            get {
                return ResourceManager.GetString("audit_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit User Id.
        /// </summary>
        internal static string audit_user_id {
            get {
                return ResourceManager.GetString("audit_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source Code.
        /// </summary>
        internal static string lead_source_code {
            get {
                return ResourceManager.GetString("lead_source_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source Id.
        /// </summary>
        internal static string lead_source_id {
            get {
                return ResourceManager.GetString("lead_source_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Source Name.
        /// </summary>
        internal static string lead_source_name {
            get {
                return ResourceManager.GetString("lead_source_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status Code.
        /// </summary>
        internal static string lead_status_code {
            get {
                return ResourceManager.GetString("lead_status_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status Id.
        /// </summary>
        internal static string lead_status_id {
            get {
                return ResourceManager.GetString("lead_status_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead Status Name.
        /// </summary>
        internal static string lead_status_name {
            get {
                return ResourceManager.GetString("lead_status_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stage Code.
        /// </summary>
        internal static string opportunity_stage_code {
            get {
                return ResourceManager.GetString("opportunity_stage_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stage Id.
        /// </summary>
        internal static string opportunity_stage_id {
            get {
                return ResourceManager.GetString("opportunity_stage_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opportunity Stage Name.
        /// </summary>
        internal static string opportunity_stage_name {
            get {
                return ResourceManager.GetString("opportunity_stage_name", resourceCulture);
            }
        }
    }
}
