//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Core.Modules.Sales.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ScrudResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ScrudResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.Core.Modules.Sales.Resources.ScrudResource", typeof(ScrudResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Id.
        /// </summary>
        internal static string account_id {
            get {
                return ResourceManager.GetString("account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Code.
        /// </summary>
        internal static string account_master_code {
            get {
                return ResourceManager.GetString("account_master_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Id.
        /// </summary>
        internal static string account_master_id {
            get {
                return ResourceManager.GetString("account_master_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Master Name.
        /// </summary>
        internal static string account_master_name {
            get {
                return ResourceManager.GetString("account_master_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string account_name {
            get {
                return ResourceManager.GetString("account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Number.
        /// </summary>
        internal static string account_number {
            get {
                return ResourceManager.GetString("account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string amount {
            get {
                return ResourceManager.GetString("amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount From.
        /// </summary>
        internal static string amount_from {
            get {
                return ResourceManager.GetString("amount_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount To.
        /// </summary>
        internal static string amount_to {
            get {
                return ResourceManager.GetString("amount_to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit Timestamp.
        /// </summary>
        internal static string audit_ts {
            get {
                return ResourceManager.GetString("audit_ts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit User Id.
        /// </summary>
        internal static string audit_user_id {
            get {
                return ResourceManager.GetString("audit_user_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Trigger on Sales.
        /// </summary>
        internal static string auto_trigger_on_sales {
            get {
                return ResourceManager.GetString("auto_trigger_on_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Rate.
        /// </summary>
        internal static string bonus_rate {
            get {
                return ResourceManager.GetString("bonus_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Code.
        /// </summary>
        internal static string bonus_slab_code {
            get {
                return ResourceManager.GetString("bonus_slab_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Detail Id.
        /// </summary>
        internal static string bonus_slab_detail_id {
            get {
                return ResourceManager.GetString("bonus_slab_detail_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field &quot;AmountTo&quot; must be greater than &quot;AmountFrom&quot;..
        /// </summary>
        internal static string bonus_slab_details_amounts_chk {
            get {
                return ResourceManager.GetString("bonus_slab_details_amounts_chk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Id.
        /// </summary>
        internal static string bonus_slab_id {
            get {
                return ResourceManager.GetString("bonus_slab_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bonus Slab Name.
        /// </summary>
        internal static string bonus_slab_name {
            get {
                return ResourceManager.GetString("bonus_slab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Frequency Id.
        /// </summary>
        internal static string checking_frequency_id {
            get {
                return ResourceManager.GetString("checking_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Rate.
        /// </summary>
        internal static string commision_rate {
            get {
                return ResourceManager.GetString("commision_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission Rate.
        /// </summary>
        internal static string commission_rate {
            get {
                return ResourceManager.GetString("commission_rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compound Item Id.
        /// </summary>
        internal static string compound_item_id {
            get {
                return ResourceManager.GetString("compound_item_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Number.
        /// </summary>
        internal static string contact_number {
            get {
                return ResourceManager.GetString("contact_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string discount {
            get {
                return ResourceManager.GetString("discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Days.
        /// </summary>
        internal static string due_days {
            get {
                return ResourceManager.GetString("due_days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Frequency Id.
        /// </summary>
        internal static string due_frequency_id {
            get {
                return ResourceManager.GetString("due_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due on Date.
        /// </summary>
        internal static string due_on_date {
            get {
                return ResourceManager.GetString("due_on_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective From.
        /// </summary>
        internal static string effective_from {
            get {
                return ResourceManager.GetString("effective_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ends On.
        /// </summary>
        internal static string ends_on {
            get {
                return ResourceManager.GetString("ends_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Code.
        /// </summary>
        internal static string frequency_code {
            get {
                return ResourceManager.GetString("frequency_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Id.
        /// </summary>
        internal static string frequency_id {
            get {
                return ResourceManager.GetString("frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency Name.
        /// </summary>
        internal static string frequency_name {
            get {
                return ResourceManager.GetString("frequency_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grace Period.
        /// </summary>
        internal static string grace_peiod {
            get {
                return ResourceManager.GetString("grace_peiod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string id {
            get {
                return ResourceManager.GetString("id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Flat Amount.
        /// </summary>
        internal static string is_flat_amount {
            get {
                return ResourceManager.GetString("is_flat_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Code.
        /// </summary>
        internal static string item_code {
            get {
                return ResourceManager.GetString("item_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Id.
        /// </summary>
        internal static string item_id {
            get {
                return ResourceManager.GetString("item_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Name.
        /// </summary>
        internal static string item_name {
            get {
                return ResourceManager.GetString("item_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Code.
        /// </summary>
        internal static string late_fee_code {
            get {
                return ResourceManager.GetString("late_fee_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Id.
        /// </summary>
        internal static string late_fee_id {
            get {
                return ResourceManager.GetString("late_fee_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Name.
        /// </summary>
        internal static string late_fee_name {
            get {
                return ResourceManager.GetString("late_fee_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Fee Posting Frequency Id.
        /// </summary>
        internal static string late_fee_posting_frequency_id {
            get {
                return ResourceManager.GetString("late_fee_posting_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Id.
        /// </summary>
        internal static string parent_account_id {
            get {
                return ResourceManager.GetString("parent_account_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Name.
        /// </summary>
        internal static string parent_account_name {
            get {
                return ResourceManager.GetString("parent_account_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Account Number.
        /// </summary>
        internal static string parent_account_number {
            get {
                return ResourceManager.GetString("parent_account_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Party Id.
        /// </summary>
        internal static string party_id {
            get {
                return ResourceManager.GetString("party_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term Code.
        /// </summary>
        internal static string payment_term_code {
            get {
                return ResourceManager.GetString("payment_term_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term Id.
        /// </summary>
        internal static string payment_term_id {
            get {
                return ResourceManager.GetString("payment_term_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Term Name.
        /// </summary>
        internal static string payment_term_name {
            get {
                return ResourceManager.GetString("payment_term_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string price {
            get {
                return ResourceManager.GetString("price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string quantity {
            get {
                return ResourceManager.GetString("quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        internal static string rate {
            get {
                return ResourceManager.GetString("rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Amount.
        /// </summary>
        internal static string recurring_amount {
            get {
                return ResourceManager.GetString("recurring_amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Frequency Id.
        /// </summary>
        internal static string recurring_frequency_id {
            get {
                return ResourceManager.GetString("recurring_frequency_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Code.
        /// </summary>
        internal static string recurring_invoice_code {
            get {
                return ResourceManager.GetString("recurring_invoice_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Id.
        /// </summary>
        internal static string recurring_invoice_id {
            get {
                return ResourceManager.GetString("recurring_invoice_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Name.
        /// </summary>
        internal static string recurring_invoice_name {
            get {
                return ResourceManager.GetString("recurring_invoice_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recurring Invoice Setup Id.
        /// </summary>
        internal static string recurring_invoice_setup_id {
            get {
                return ResourceManager.GetString("recurring_invoice_setup_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot have more than one auto trigger on sales for this item..
        /// </summary>
        internal static string recurring_invoices_item_id_auto_trigger_on_sales_uix {
            get {
                return ResourceManager.GetString("recurring_invoices_item_id_auto_trigger_on_sales_uix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team Code.
        /// </summary>
        internal static string sales_team_code {
            get {
                return ResourceManager.GetString("sales_team_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team Id.
        /// </summary>
        internal static string sales_team_id {
            get {
                return ResourceManager.GetString("sales_team_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Team Name.
        /// </summary>
        internal static string sales_team_name {
            get {
                return ResourceManager.GetString("sales_team_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Bonus Setup Id.
        /// </summary>
        internal static string salesperson_bonus_setup_id {
            get {
                return ResourceManager.GetString("salesperson_bonus_setup_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Code.
        /// </summary>
        internal static string salesperson_code {
            get {
                return ResourceManager.GetString("salesperson_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Id.
        /// </summary>
        internal static string salesperson_id {
            get {
                return ResourceManager.GetString("salesperson_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson Name.
        /// </summary>
        internal static string salesperson_name {
            get {
                return ResourceManager.GetString("salesperson_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slab Name.
        /// </summary>
        internal static string slab_name {
            get {
                return ResourceManager.GetString("slab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts From.
        /// </summary>
        internal static string starts_from {
            get {
                return ResourceManager.GetString("starts_from", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub Total.
        /// </summary>
        internal static string sub_total {
            get {
                return ResourceManager.GetString("sub_total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sys Type.
        /// </summary>
        internal static string sys_type {
            get {
                return ResourceManager.GetString("sys_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string tax {
            get {
                return ResourceManager.GetString("tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string total {
            get {
                return ResourceManager.GetString("total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sales.
        /// </summary>
        internal static string total_sales {
            get {
                return ResourceManager.GetString("total_sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Name.
        /// </summary>
        internal static string unit_name {
            get {
                return ResourceManager.GetString("unit_name", resourceCulture);
            }
        }
    }
}
