DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS core CASCADE;
DROP SCHEMA IF EXISTS office CASCADE;
DROP SCHEMA IF EXISTS policy CASCADE;
DROP SCHEMA IF EXISTS transactions CASCADE;
DROP SCHEMA IF EXISTS crm CASCADE;
DROP SCHEMA IF EXISTS mrp CASCADE;


CREATE SCHEMA audit;
CREATE SCHEMA core;
CREATE SCHEMA office;
CREATE SCHEMA policy;
CREATE SCHEMA transactions;
CREATE SCHEMA crm;
CREATE SCHEMA mrp;