//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MixERP.Net.Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Warnings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Warnings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MixERP.Net.Common.Resources.Warnings", typeof(Warnings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Delivery&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryDelivery {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Direct&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryDirect {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Invoice&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryInvoice {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Order&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryOrder {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Payment&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryPayment {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Quotation&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryQuotation {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Receipt&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryReceipt {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Inventory Return&quot;.
        /// </summary>
        internal static string InvalidSubTranBookInventoryReturn {
            get {
                return ResourceManager.GetString("InvalidSubTranBookInventoryReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Purchase Delivery&quot;.
        /// </summary>
        internal static string InvalidSubTranBookPurchaseDelivery {
            get {
                return ResourceManager.GetString("InvalidSubTranBookPurchaseDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Purchase Quotation&quot;.
        /// </summary>
        internal static string InvalidSubTranBookPurchaseQuotation {
            get {
                return ResourceManager.GetString("InvalidSubTranBookPurchaseQuotation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Purchase Suspense&quot;.
        /// </summary>
        internal static string InvalidSubTranBookPurchaseSuspense {
            get {
                return ResourceManager.GetString("InvalidSubTranBookPurchaseSuspense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Purchase Transfer&quot;.
        /// </summary>
        internal static string InvalidSubTranBookPurchaseTransfer {
            get {
                return ResourceManager.GetString("InvalidSubTranBookPurchaseTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Sales Payment&quot;.
        /// </summary>
        internal static string InvalidSubTranBookSalesPayment {
            get {
                return ResourceManager.GetString("InvalidSubTranBookSalesPayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Sales Suspense&quot;.
        /// </summary>
        internal static string InvalidSubTranBookSalesSuspense {
            get {
                return ResourceManager.GetString("InvalidSubTranBookSalesSuspense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid SubTranBook &quot;Sales Transfer&quot;.
        /// </summary>
        internal static string InvalidSubTranBookSalesTransfer {
            get {
                return ResourceManager.GetString("InvalidSubTranBookSalesTransfer", resourceCulture);
            }
        }
    }
}
